import crypto from "node:crypto";
import path from "node:path";

import { artifactEvidenceRole, inspectDeclaredPath, normalizeProjectRelativePath } from "./artifact-integrity.mjs";
import { assertNotDoveLessonArtifactPath } from "./domain-artifacts.mjs";
import { assertMissionAcceptsWrites } from "./mission-graph.mjs";
import { currentMutationContext } from "./mutation-backend.mjs";
import { createResearchHandoff, validateResearchHostOutcome } from "./research-handoff.mjs";
import { snapshotArtifactBuffer } from "./review-artifact-snapshot.mjs";
import { ARTIFACT_PATHS } from "./schema.mjs";
import { assertReceiptAppendable, deriveArtifactReferences, EXECUTION_RECEIPT_SCHEMA_VERSION } from "./receipt-ledger.mjs";
import { createValidationRecord } from "./validation-records.mjs";
import { assertGovernanceMutationRegistered, writeJson } from "./workspace.mjs";
import { openDoveWorkspace, stableWorkspaceSerialize } from "./workspace-schema.mjs";

const RECORD_FIELDS = new Set(["missionId", "decisionRevision", "attemptId", "status", "performedActionCount", "actualUsage", "evidenceReturned", "artifactPaths", "validationPaths", "facts", "startedAt", "finishedAt"]);
const FOUR_HOURS_MS = 4 * 60 * 60 * 1000;

function plain(value, label) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be a plain object.`); }
function sealed(value, fields, label) { plain(value, label); const unknown = Object.keys(value).filter((field) => !fields.has(field)); if (unknown.length) throw new Error(`${label} does not accept unknown fields: ${unknown.join(", ")}.`); }
function safeId(value, label) { if (typeof value !== "string" || !/^[a-z0-9][a-z0-9._-]{0,127}$/u.test(value)) throw new Error(`${label} must be a safe lowercase identifier.`); return value; }
function sha256(value) { return crypto.createHash("sha256").update(typeof value === "string" || Buffer.isBuffer(value) ? value : stableWorkspaceSerialize(value)).digest("hex"); }
function inspectPaths(root, values, label) { if (!Array.isArray(values)) throw new Error(`${label} must be an array.`); const result = values.map((rawPath, index) => { const normalized = normalizeProjectRelativePath(rawPath); if (!normalized.ok || normalized.normalizedPath !== rawPath) throw new Error(`${label}[${index}] must be a canonical project-relative path.`); const inspection = inspectDeclaredPath(root, rawPath, { requireNonEmpty: true, rejectBookkeeping: true }); if (inspection.status !== "existing") throw new Error(`${label}[${index}] must be an existing non-empty file.`); assertNotDoveLessonArtifactPath(rawPath, `${label}[${index}]`); const snapshot = snapshotArtifactBuffer(root, rawPath, `${label}[${index}]`); return { path: snapshot.path, sha256: snapshot.sha256 }; }); if (new Set(result.map((item) => item.path)).size !== result.length) throw new Error(`${label} must not contain duplicates.`); return result; }
function callbackDigest(args, decision, outcome, artifacts, validations) { return sha256({ attemptId: args.attemptId, missionId: decision.missionId, decisionDigest: decision.decisionDigest, actionId: decision.nextAction.actionId, actionDigest: decision.nextAction.actionDigest, status: outcome.status, performedActionCount: outcome.performedActionCount, actualUsage: outcome.actualUsage, evidenceReturned: [...outcome.evidenceReturned], artifacts: artifacts.map(({ path: artifactPath, sha256: artifactSha256 }) => ({ path: artifactPath, sha256: artifactSha256 })), validations: validations.map(({ path: validationPath, sha256: validationSha256 }) => ({ path: validationPath, sha256: validationSha256 })), facts: [...outcome.facts], startedAt: outcome.startedAt, finishedAt: outcome.finishedAt }); }

export function recordResearchOutcome(root, args = {}) {
  assertGovernanceMutationRegistered("record-research-outcome", "guarded"); sealed(args, RECORD_FIELDS, "recordResearchOutcome"); const context = currentMutationContext(root); if (!context || context.mutationMode !== "direct-process") throw new Error("recordResearchOutcome requires one direct-process MutationContext.");
  const missionId = safeId(args.missionId, "missionId"); const attemptId = safeId(args.attemptId, "attemptId"); const workspace = openDoveWorkspace(root, { operation: "Research outcome closure" }); const mission = workspace.missions.get(missionId); if (!mission || mission.mode !== "research") throw new Error("Research outcome closure requires an existing research mission."); assertMissionAcceptsWrites(workspace, mission, { receipt: true });
  const decision = workspace.currentResearchDecisions.get(missionId); if (!decision || decision.revision !== args.decisionRevision || !decision.nextAction) throw new Error("The current research decision is stale or does not authorize an action.");
  const handoff = createResearchHandoff(decision, { issuedAt: decision.createdAt, expiresAt: new Date(Date.parse(decision.createdAt) + FOUR_HOURS_MS).toISOString() }); const now = new Date().toISOString();
  const outcome = validateResearchHostOutcome(handoff, { status: args.status, performedActionCount: args.performedActionCount, actualUsage: args.actualUsage, evidenceReturned: args.evidenceReturned, facts: args.facts, claims: [], startedAt: args.startedAt, finishedAt: args.finishedAt }, { missionId: decision.missionId, contractDigest: decision.contractDigest, decisionDigest: decision.decisionDigest, currentEnvelopeId: handoff.envelopeId, supersededEnvelopeIds: [], now });
  if (outcome.scopeDeviationReasons.some((reason) => reason.startsWith("unexpected-evidence:"))) throw new Error("Returned evidence does not match the current research handoff."); if (outcome.status === "completed" && outcome.performedActionCount !== 1) throw new Error("A completed research outcome must report the authorized action exactly once.");
  const artifacts = inspectPaths(root, args.artifactPaths, "artifactPaths"); const validationFiles = inspectPaths(root, args.validationPaths, "validationPaths"); const allPaths = [...artifacts, ...validationFiles].map((item) => item.path); if (new Set(allPaths).size !== allPaths.length) throw new Error("Research outcome artifact and validation paths must be distinct.");
  const ownerByPath = new Map(workspace.receiptLedger.currentOwnership.map((item) => [item.path, item]));
  for (const artifact of artifacts) {
    const role = artifactEvidenceRole(artifact.path);
    const owner = ownerByPath.get(artifact.path);
    if (!owner && role !== "external-project") throw new Error(`Research outcome cannot claim an unowned Dove domain artifact: ${artifact.path}.`);
    if (owner && owner.missionId !== missionId) throw new Error(`Research outcome artifact is owned by another mission: ${artifact.path}.`);
    if (owner && owner.sha256 !== artifact.sha256 && role !== "external-project") throw new Error(`Research outcome cannot claim a changed Dove domain artifact: ${artifact.path}.`);
  }
  const digest = callbackDigest(args, decision, outcome, artifacts, validationFiles); const existing = workspace.receiptLedger.receipts.find((receipt) => receipt.researchOutcome?.attemptId === attemptId);
  if (existing) { if (existing.researchOutcome.callbackDigest === digest) return { status: "replayed", zeroWrite: true, receipt: existing, awaitingReevaluation: !decision.consumedReceiptIds.includes(existing.receiptId), writes: [] }; throw new Error("The research attemptId was already recorded with different immutable content."); }
  const receiptId = `receipt-research-${sha256({ missionId, attemptId }).slice(0, 24)}`; const primary = artifacts[0] ?? null;
  const validations = validationFiles.map((item) => createValidationRecord({ kind: "validation-log", result: outcome.status === "completed" ? "passed" : outcome.status === "failed" ? "failed" : "incomplete", level: "integration", producerKind: "dove-internal", producerOperation: "record-research-outcome", observedExitStatus: null, targetReference: primary ? `artifact:${primary.path}` : `validation:${item.path}`, targetHash: primary?.sha256 ?? item.sha256, reference: item.path, outputHash: item.sha256 }, { label: item.path }));
  const baseReceipt = { schemaVersion: EXECUTION_RECEIPT_SCHEMA_VERSION, workspaceId: workspace.manifest.workspaceId, receiptId, ledgerSequence: workspace.receiptLedger.nextLedgerSequence, missionId, contractDigest: mission.contractDigest, summary: `Research action ${outcome.status}; scientific interpretation remains pending.`, artifacts: artifacts.map((item) => ({ ...item, kind: "other" })), validations, criteriaSatisfied: [], producedAt: outcome.finishedAt, recordedAt: now, producer: { kind: "dove-internal", actionId: "record-research-outcome" }, researchOutcome: { attemptId, decisionId: decision.decisionId, decisionDigest: decision.decisionDigest, actionId: decision.nextAction.actionId, actionDigest: decision.nextAction.actionDigest, envelopeId: handoff.envelopeId, status: outcome.status, evidenceReturned: [...outcome.evidenceReturned], actualUsage: { ...outcome.actualUsage }, facts: [...outcome.facts], startedAt: outcome.startedAt, finishedAt: outcome.finishedAt, callbackDigest: digest } };
  const receipt = { ...baseReceipt, artifacts: deriveArtifactReferences(baseReceipt) }; context.requireCommitPrecondition(ARTIFACT_PATHS.executionReceiptsDir); context.requireCommitLock(".dove/.receipt-ledger-append.lock", { label: "Execution receipt ledger append lock" }); assertReceiptAppendable(workspace.receiptLedger, receipt, { artifactHandoffs: workspace.artifactHandoffs }); writeJson(root, path.posix.join(ARTIFACT_PATHS.executionReceiptsDir, `${receiptId}.json`), receipt);
  return { status: "recorded", accepted: true, evidenceComplete: outcome.missingRequiredEvidence.length === 0, missingRequiredEvidence: outcome.missingRequiredEvidence, scopeDeviation: outcome.scopeDeviation, scopeDeviationReasons: outcome.scopeDeviationReasons, outcomeStatus: outcome.status, performedActionCount: outcome.performedActionCount, receipt, awaitingReevaluation: true, decision, writes: [path.posix.join(ARTIFACT_PATHS.executionReceiptsDir, `${receiptId}.json`)] };
}
